
index:
  slogan:
    enable: true
    text: å…±åŒè¿›æ­¥ Fsmt

navbar:
  blog_title: Fsmt blog
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

post:
  comments:
    enable: true
    type: utterances
  updated:
    enable: true
  copyright:
    license: 'BY-NC-SA'


utterances:
  repo: firstmetcs/blog-comments
  issue_term: pathname
  label: #
  theme: github-light
  crossorigin: anonymous

web_analytics:  # ç½‘é¡µè®¿é—®ç»Ÿè®¡
  enable: true
  baidu: cedb334c71d9c14c4f0337d5e60aa43c

about:
  enable: true
  avatar: https://firstmetcs.net/5.06ZF05/img/ava.jpg
  name: "firstmetcs"
  intro: "å…±åŒè¿›æ­¥ Fsmt"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/firstmetcs', tip: 'GitHub' }
    - { class: 'iconfont icon-mini-program-fill', link: 'https://firstmetcs.net', tip: 'fsmt' }
    - { class: 'iconfont icon-rss-fill', link: 'https://blog.firstmetcs.net/atom.xml', tip: 'RSS' }

favicon: /img/f.png
apple_touch_icon: /img/f.png

footer:
  content: '<div style="font-size: 0.85rem">Â© 2015-2023 <a href="https://firstmetcs.net" target="_blank">firstmetcs.net</a> ç‰ˆæƒæ‰€æœ‰</div>'
  beian:
    enable: true
    icp_text: äº¬ICPå¤‡2023003449å·
    police_text: äº¬å…¬ç½‘å®‰å¤‡11010502051927å·
    police_code: 11010502051927

custom_js: //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/caidai.js
#custom_js: //cdn.jsdelivr.net/gh/hustcc/ribbon.js/dist/ribbon.min.js

links:
  items:
    - {
      title: 'Hexo Docs',
      intro: 'å¿«é€Ÿã€ç®€æ´ä¸”é«˜æ•ˆçš„åšå®¢æ¡†æ¶',
      link: 'https://hexo.io/',
      avatar: 'https://hexo.io/logo.svg'
    }
    - {
      title: 'Fluid Docs',
      intro: 'ä¸»é¢˜ä½¿ç”¨æŒ‡å—',
      link: 'https://hexo.fluid-dev.com/docs/',
      avatar: 'https://hexo.fluid-dev.com/docs/fluid_hexo.png'
    }
    - {
      title: 'Firstmetcs',
      intro: 'ç§‹æ°´é™è½©',
      link: 'https://firstmetcs.net',
      avatar: '/img/f.png'
    }
  default_avatar: /img/avatar.png
  custom:
    enable: true
    content: '<hr><p>æœ‹å‹ï¼Œä½ å¥½å‘€ï¼</p><p>ä½ å¯ä»¥åœ¨ä¸‹æ–¹ç•™è¨€æ¥åŠ å…¥æˆ‘çš„å‹é“¾ï¼Œæä¾›çš„ä¿¡æ¯å‚è€ƒï¼š</p><ul><li>åšå®¢åï¼šFluid</li><li>ç®€ä»‹ï¼šFluid ä¸»é¢˜å®˜æ–¹åšå®¢</li><li>é“¾æ¥ï¼šhttps://hexo.fluid-dev.com</li><li>å›¾ç‰‡ï¼šhttps://hexo.fluid-dev.com/img/favicon.png</li></ul>æœ¬ç«™ä¿¡æ¯è¯·è¯„è®ºåŒºä¸€æ¥¼ğŸ‘‡ğŸ»ï¼'
  comments:
    enable: true
    type: utterances
